// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzzbfy0qdpj8x5Z0G5ihGchHAO4u6U8A',
    appId: '1:441846428818:web:5f97e52851efcbd4d5e24b',
    messagingSenderId: '441846428818',
    projectId: 'se-n13-your-pets',
    authDomain: 'se-n13-your-pets.firebaseapp.com',
    storageBucket: 'se-n13-your-pets.appspot.com',
    measurementId: 'G-5HCRC5JZ7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvQ1lMpYy8vjqcYtX4ljcYBndBcMY7ic',
    appId: '1:441846428818:android:35dbecd643aa1efdd5e24b',
    messagingSenderId: '441846428818',
    projectId: 'se-n13-your-pets',
    storageBucket: 'se-n13-your-pets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBBDG4jRP1hJSYGEySFb1eaju6YHqMvps',
    appId: '1:441846428818:ios:c0ac4c0d833a1bbcd5e24b',
    messagingSenderId: '441846428818',
    projectId: 'se-n13-your-pets',
    storageBucket: 'se-n13-your-pets.appspot.com',
    iosClientId: '441846428818-4qk42cciglup3uo11ghnrvfmr7430150.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBBDG4jRP1hJSYGEySFb1eaju6YHqMvps',
    appId: '1:441846428818:ios:c0ac4c0d833a1bbcd5e24b',
    messagingSenderId: '441846428818',
    projectId: 'se-n13-your-pets',
    storageBucket: 'se-n13-your-pets.appspot.com',
    iosClientId: '441846428818-4qk42cciglup3uo11ghnrvfmr7430150.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
